/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gymmanagement;

/**
 *
 * @author hp
 */
public class AddCoachDialog extends javax.swing.JDialog {
     // متغيرات برمجية لحفظ البيانات وتمريرها للشاشة الرئيسية
    private boolean succeeded = false;
    private boolean isEditMode = false;
    
    public boolean isSucceeded() { return succeeded; }
    public String getCoachName() { return txtCoachName.getText().trim(); }
    public String getSpecialization() { return cmbSpecialization.getSelectedItem() != null ? cmbSpecialization.getSelectedItem().toString() : "";  }
    public String getCoachPhone() { return txtCoachPhone.getText().trim(); }
    
    // دالة لتعبئة البيانات تلقائياً عند وضع التعديل
    public void setCoachData(String name, String spec, String phone) {
        this.txtCoachName.setText(name);
         this.cmbSpecialization.setSelectedItem(spec); // تعديل التحديد بناءً على القيمة القادمة
        this.txtCoachPhone.setText(phone);
        this.isEditMode = true;
        this.btnSaveCoach.setText("Update");
    }
    /**
     * Creates new form AddCoachDialog
     */
    public AddCoachDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtCoachName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCoachPhone = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSaveCoach = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbSpecialization = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setText("Phone : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));
        getContentPane().add(txtCoachName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 140, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setText("Coach Name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setText("Specialization : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        getContentPane().add(txtCoachPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 140, -1));

        btnCancel.setBackground(new java.awt.Color(204, 204, 255));
        btnCancel.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        btnSaveCoach.setBackground(new java.awt.Color(204, 204, 255));
        btnSaveCoach.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnSaveCoach.setText("Save");
        btnSaveCoach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCoachActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaveCoach, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\oop project gym\\logo.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setText("Add New Coach");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        cmbSpecialization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fitness", "Bodybuilding", "Cardio", "CrossFit", "Nutrition" }));
        getContentPane().add(cmbSpecialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveCoachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCoachActionPerformed
        // TODO add your handling code here:
         // 1. التحقق من الحقول
    if (txtCoachName.getText().trim().isEmpty() || txtCoachPhone.getText().trim().isEmpty() || cmbSpecialization.getSelectedItem() == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // 2. تأكيد الحفظ وإغلاق الشاشة
    succeeded = true;
    this.dispose();
          

    }//GEN-LAST:event_btnSaveCoachActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
       
        this.dispose();

    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCoachDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCoachDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCoachDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCoachDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddCoachDialog dialog = new AddCoachDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSaveCoach;
    private javax.swing.JComboBox<String> cmbSpecialization;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCoachName;
    private javax.swing.JTextField txtCoachPhone;
    // End of variables declaration//GEN-END:variables
}
