/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gymmanagement;

/**
 *
 * @author hp
 */
public class AddMemberDialog extends javax.swing.JDialog {
    // متغير مخفي لمعرفة حالة الشاشة: true تعني تعديل، false تعني إضافة جديدة
    private boolean isEditMode = false;
    /**
     * Creates new form AddMemberDialog
     */
    public AddMemberDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null); // لجعل الشاشة تفتح في منتصف الشاشة تلقائياً
        
    }
    // دالة عامة (Public Method) تسمح بتمرير البيانات بأمان ومطابقة لشروط الـ OOP
    public void setMemberData(String name, String phone, String plan) {
      this.txtName.setText(name);
      this.txtPhone.setText(phone);
      this.cmbPlan.setSelectedItem(plan);
      
      this.isEditMode= true;  //قلب الحالة وضع التعديل برمجيا 
      this.btnSave.setText("Update"); // تغيير اسم الزر عند التعديل
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbPlan = new javax.swing.JComboBox<>();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setText("Add New Member");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 150, 30));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setText("Subscription  :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setText("Member Name : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 150, 30));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setText("Number Phone :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        cmbPlan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monthly", "Months 3", "Annual" }));
        getContentPane().add(cmbPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 100, -1));

        btnCancel.setBackground(new java.awt.Color(204, 204, 255));
        btnCancel.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        btnSave.setBackground(new java.awt.Color(204, 204, 255));
        btnSave.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\oop project gym\\logo.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 110, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose(); // يسكر الشاشة المنبثقة فقط ويرجعنا للجدول
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
         // 1. قراءة البيانات والتحقق منها كالعادة
String name = txtName.getText().trim();
String phone = txtPhone.getText().trim();
String plan = cmbPlan.getSelectedItem().toString();

if (name.isEmpty() || phone.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "الرجاء تعبئة جميع الحقول!", "خطأ", javax.swing.JOptionPane.ERROR_MESSAGE);
    return;
}

// 2. الوصول للجدول وتحديثه أو الإضافة فيه
try {
    java.awt.Window[] windows = java.awt.Window.getWindows();
    for (java.awt.Window window : windows) {
        if (window instanceof javax.swing.JFrame && window.isVisible()) {
            javax.swing.JFrame mainFrame = (javax.swing.JFrame) window;
            for (java.awt.Component comp : mainFrame.getContentPane().getComponents()) {
                if (comp instanceof javax.swing.JPanel) {
                    javax.swing.JPanel contentPanel = (javax.swing.JPanel) comp;
                    for (java.awt.Component subComp : contentPanel.getComponents()) {
                        if (subComp.getClass().getName().endsWith("MembersPanel")) {
                            javax.swing.JPanel membersPanel = (javax.swing.JPanel) subComp;
                            for (java.awt.Component panelComp : membersPanel.getComponents()) {
                                if (panelComp instanceof javax.swing.JScrollPane) {
                                    javax.swing.JScrollPane scrollPane = (javax.swing.JScrollPane) panelComp;
                                    if (scrollPane.getViewport().getView() instanceof javax.swing.JTable) {
                                        javax.swing.JTable table = (javax.swing.JTable) scrollPane.getViewport().getView();
                                        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) table.getModel();
                                        
                                        // 🌟 الفحص الذكي بناءً على المتغير المخفي
                                        if (isEditMode) {
                                            // لو في وضع التعديل، نعدل السطر الحالي
                                            int selectedRow = table.getSelectedRow();
                                            if (selectedRow != -1) {
                                                model.setValueAt(name, selectedRow, 0);  
                                                model.setValueAt(phone, selectedRow, 1); 
                                                model.setValueAt(plan, selectedRow, 2);  
                                            }
                                        } else {
                                            // لو مش تعديل (إضافة جديدة)، يضيف سطر جديد
                                            model.addRow(new Object[]{name, phone, plan});
                                        }
                                        
                                        this.dispose(); // إغلاق الشاشة
                                        return;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "خطأ: " + e.getMessage());
}
        
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMemberDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMemberDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMemberDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMemberDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddMemberDialog dialog = new AddMemberDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbPlan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
