/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gymmanagement;

/**
 *
 * @author hp
 */
public class AddMemberDialog extends javax.swing.JDialog {
    // متغير مخفي لمعرفة حالة الشاشة: true تعني تعديل، false تعني إضافة جديدة
    private boolean isEditMode = false;
    // متغيرات لحفظ البيانات المدخلة بشكل مؤقت لتمريرها للشاشة الرئيسية
    private boolean succeeded = false;
    
    public boolean isSucceeded() { return succeeded; }
    public String getMemberName() { return txtName.getText().trim(); }
    public String getMemberPhone() { return txtPhone.getText().trim(); }
    public String getSelectedSubscription() { return cmbSubscription.getSelectedItem() != null ? cmbSubscription.getSelectedItem().toString() : ""; }
    /**
     * Creates new form AddMemberDialog
     */
    // Constructor ذكي يستقبل جدول الاشتراكات ويعبي الـ ComboBox تلقائياً
     public AddMemberDialog(java.awt.Frame parent, boolean modal, javax.swing.table.DefaultTableModel subscriptionModel) {
        
        super(parent, modal);
         initComponents();
    
    // تعبئة الـ ComboBox بالبيانات القادمة من جدول الاشتراكات
         cmbSubscription.removeAllItems();
        for (int i = 0; i < subscriptionModel.getRowCount(); i++) {
            String planName = subscriptionModel.getValueAt(i, 0).toString();
            cmbSubscription.addItem(planName);
        }
    }
        // Constructor إضافي (Overloading) عشان يخلي الأزرار القديمة تشتغل بدون خطأ
    public AddMemberDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    } 
     
    // دالة عامة (Public Method) تسمح بتمرير البيانات بأمان ومطابقة لشروط الـ OOP
    public void setMemberData(String name, String phone, String plan) {
      this.txtName.setText(name);
      this.txtPhone.setText(phone);
      this.cmbSubscription.setSelectedItem(plan);
      
      this.isEditMode= true;  //قلب الحالة وضع التعديل برمجيا 
      this.btnSave.setText("Update"); // تغيير اسم الزر عند التعديل
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbSubscription = new javax.swing.JComboBox<>();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtEndDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setText("Add New Member");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 150, 30));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setText("End Date  :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setText("Member Name : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 150, 30));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setText("Number Phone :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        cmbSubscription.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monthly", "Months 3", "Months 6", "Annual" }));
        cmbSubscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSubscriptionActionPerformed(evt);
            }
        });
        getContentPane().add(cmbSubscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 100, -1));

        btnCancel.setBackground(new java.awt.Color(204, 204, 255));
        btnCancel.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        btnSave.setBackground(new java.awt.Color(204, 204, 255));
        btnSave.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\oop project gym\\logo.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 110, 110));
        getContentPane().add(txtEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 140, 30));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel6.setText("Subscription  :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose(); // يسكر الشاشة المنبثقة فقط ويرجعنا للجدول
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
          
        // 1. التحقق من أن الخانات مش فاضية (Validation)
        if (txtName.getText().trim().isEmpty() || txtPhone.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "الرجاء تعبئة جميع الحقول المطلوبة!", "تنبيه", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
        // 2. التحقق من أن المستخدم اختار اشتراك فعلاً
        if (cmbSubscription.getSelectedItem() == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "الرجاء اختيار نوع الاشتراك!", "تنبيه", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
        // 3. تأكيد النجاح وإغلاق الشاشة
        succeeded = true;
        this.dispose(); 

    }//GEN-LAST:event_btnSaveActionPerformed

    private void cmbSubscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSubscriptionActionPerformed
        // TODO add your handling code here:
           // 1. التأكد من أن المستخدم اختار حاجة فعلاً ومش فاضي
    if (cmbSubscription.getSelectedItem() == null) return;
    
    String selectedPlan = cmbSubscription.getSelectedItem().toString().toLowerCase();
    
    // 2. الحصول على تاريخ اليوم كبداية للاشتراك
    java.time.LocalDate startDate = java.time.LocalDate.now();
    java.time.LocalDate endDate = startDate; // افتراضي
    
    // 3. حسبة المدة بناءً على اسم الاشتراك المحدد
    if (selectedPlan.contains("monthly") || selectedPlan.contains("شهر")) {
        endDate = startDate.plusMonths(1);
    } else if (selectedPlan.contains("3 months") || selectedPlan.contains("3 أشهر")) {
        endDate = startDate.plusMonths(3);
    } else if (selectedPlan.contains("6 months") || selectedPlan.contains("6 أشهر")) {
        endDate = startDate.plusMonths(6);
    } else if (selectedPlan.contains("annual")|| selectedPlan.contains("year") || selectedPlan.contains("سنة")) {
        endDate = startDate.plusYears(1);
    } else {
        // لو اشتراك مخصص، نزيدوا شهر افتراضي
        endDate = startDate.plusMonths(1); 
    }
    
    // 4. صيغة التاريخ وتحديث الخانة (تأكدي من اسم تيكست التاريخ عندك، افترضناه txtEndDate)
    java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd");
    txtEndDate.setText(endDate.format(formatter));
    }//GEN-LAST:event_cmbSubscriptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMemberDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMemberDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMemberDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMemberDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddMemberDialog dialog = new AddMemberDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbSubscription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables

      public void populateSubscriptionComboBox(javax.swing.table.DefaultTableModel subscriptionTableModel) {
    // 1. تنظيف الـ ComboBox من أي خيارات قديمة
         cmbSubscription.removeAllItems();
    
    // 2. الدوران على أسطر جدول الاشتراكات وسحب الأسماء
         for (int i = 0; i < subscriptionTableModel.getRowCount(); i++) {
             String planName = subscriptionTableModel.getValueAt(i, 0).toString();
            cmbSubscription.addItem(planName); // إضافة اسم الاشتراك للقائمة
        }
     }
}
