/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gymmanagement;

/**
 *
 * @author hp
 */
public class AddSubscriptionDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddSubscriptionDialog
     */
    // flag لمعرفة هل العملية إضافة أم تعديل
    private boolean isEditMode = false;
    // متغير لحفظ حالة الضغط على زر Save (هل تم الحفظ أم تم الإلغاء)
    private boolean saved = false;
    
     // 1. الـ Constructor الافتراضي لحالة الإضافة (Add)
    public AddSubscriptionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Add New Subscription");
        lblTitle.setText("Add New Subscription"); // لتغيير العنوان الداخلي اللي درتيه
        setLocationRelativeTo(null);
    }

    // 2. الـ Constructor الثاني لحالة التعديل (Edit)
    public AddSubscriptionDialog(java.awt.Frame parent, boolean modal, String name, double price, String duration) {
        super(parent, modal);
        initComponents();
        this.isEditMode = true; // تفعيل وضع التعديل
        
        setTitle("Update Subscription");
        lblTitle.setText("Update Subscription"); // تغيير العنوان الداخلي ليناسب التعديل
        setLocationRelativeTo(null);
        
        // تعبئة البيانات القديمة في الحقول عشان المستخدم يعدلها
        txtSubscriptionName.setText(name);
        txtPrice.setText(String.valueOf(price));
        cmbDuration.setSelectedItem(duration);
    }
     // دالة لمعرفة هل ضغط المستخدم على Save أو لا
    public boolean isSaved() {
        return saved;
    }

    // دالة لتبسيط قراءة البيانات المدخلة من الشاشة الرئيسية
    public String getSubscriptionName() {
        return txtSubscriptionName.getText().trim();
    }

    public double getPrice() {
        try {
            return Double.parseDouble(txtPrice.getText().trim());
        } catch (NumberFormatException e) {
            return 0.0;
        }
    }

    public String getDuration() {
        return cmbDuration.getSelectedItem().toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSubscriptionName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbDuration = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel1.setText("Subscription Name : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));
        getContentPane().add(txtSubscriptionName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 161, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setText("Price : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 71, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setText("Duration : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        cmbDuration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month 1", "Months 3", "Months 6", "Months 12" }));
        getContentPane().add(cmbDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        btnSave.setBackground(new java.awt.Color(204, 204, 255));
        btnSave.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        btnCancel.setBackground(new java.awt.Color(204, 204, 255));
        btnCancel.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        lblTitle.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        lblTitle.setText("Subscription Details");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
         saved = false;
         dispose(); // إغلاق النافذة
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
         // التأكد من أن الحقول ليست فارغة
         if (getSubscriptionName().isEmpty() || txtPrice.getText().trim().isEmpty()) {
             javax.swing.JOptionPane.showMessageDialog(this, "Please fill all fields!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
             return;
         }
    
           // إذا كانت البيانات تمام
           saved = true;
           dispose(); // إغلاق النافذة بنجاح
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSubscriptionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSubscriptionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSubscriptionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSubscriptionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run() {
                AddSubscriptionDialog dialog = new AddSubscriptionDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbDuration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSubscriptionName;
    // End of variables declaration//GEN-END:variables
}
