/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gymmanagement;

/**
 *
 * @author hp
 */
public class CoachesPanel extends javax.swing.JPanel {

    /**
     * Creates new form CoachesPanel
     */
    private String role;

    // الـ Constructor الجديد اللي يستقبل الدور
    public CoachesPanel(String role) {
        initComponents();
        this.role = role;
        
        // لو اللي داخل ريسبشن، اخفي عليه زر الحذف فوراً داخل شاشته!
        if (role != null && role.equalsIgnoreCase("Receptionist")) {
            btnDeleteCoach.setVisible(false); 
        }
    }

    // خلّي الـ Constructor القديم الفاضي قاعد للاحتياط عشان ما يضربش التصميم
    public CoachesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableCoaches = new javax.swing.JTable();
        btnDeleteCoach = new javax.swing.JButton();
        btnAddCoach1 = new javax.swing.JButton();
        btnEditCoach1 = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableCoaches.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coach Name", "Specialization", "Phone"
            }
        ));
        jScrollPane1.setViewportView(tableCoaches);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 330, 160));

        btnDeleteCoach.setBackground(new java.awt.Color(204, 204, 255));
        btnDeleteCoach.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnDeleteCoach.setText("Delete");
        btnDeleteCoach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCoachActionPerformed(evt);
            }
        });
        add(btnDeleteCoach, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        btnAddCoach1.setBackground(new java.awt.Color(204, 204, 255));
        btnAddCoach1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnAddCoach1.setText("Add Coach");
        btnAddCoach1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCoach1ActionPerformed(evt);
            }
        });
        add(btnAddCoach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        btnEditCoach1.setBackground(new java.awt.Color(204, 204, 255));
        btnEditCoach1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnEditCoach1.setText("Edit Data");
        btnEditCoach1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCoach1ActionPerformed(evt);
            }
        });
        add(btnEditCoach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        lblTitle.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        lblTitle.setText("Manage Coaches");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCoach1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCoach1ActionPerformed
        // TODO add your handling code here:
         
    java.awt.Frame parentFrame = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
    AddCoachDialog dialog = new AddCoachDialog(parentFrame, true);
    dialog.setVisible(true);
    
    // بعد إغلاق الشاشة، نتحققوا لو ضغط على Save
    if (dialog.isSucceeded()) {
        String name = dialog.getCoachName();
        String spec = dialog.getSpecialization();
        String phone = dialog.getCoachPhone();
        
        // إضافة الصف لجدول الكباتن (تأكدي من الاسم tableCoaches)
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tableCoaches.getModel();
        model.addRow(new Object[]{name, spec, phone});
        
        javax.swing.JOptionPane.showMessageDialog(this, "Coach added successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    
}
    }//GEN-LAST:event_btnAddCoach1ActionPerformed

    private void btnEditCoach1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCoach1ActionPerformed
        // TODO add your handling code here:
         int selectedRow = tableCoaches.getSelectedRow();
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a coach to edit!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // سحب البيانات الحالية
    String currentName = tableCoaches.getValueAt(selectedRow, 0).toString();
    String currentSpec = tableCoaches.getValueAt(selectedRow, 1).toString();
    String currentPhone = tableCoaches.getValueAt(selectedRow, 2).toString();
    
    java.awt.Frame parentFrame = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
    AddCoachDialog dialog = new AddCoachDialog(parentFrame, true);
    
    // تمرير البيانات للـ Dialog قبل ما يفتح
    dialog.setCoachData(currentName, currentSpec, currentPhone);
    dialog.setVisible(true);
    
    // تحديث الجدول لو تم التعديل
    if (dialog.isSucceeded()) {
        tableCoaches.setValueAt(dialog.getCoachName(), selectedRow, 0);
        tableCoaches.setValueAt(dialog.getSpecialization(), selectedRow, 1);
        tableCoaches.setValueAt(dialog.getCoachPhone(), selectedRow, 2);
        
        javax.swing.JOptionPane.showMessageDialog(this, "Coach data updated successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_btnEditCoach1ActionPerformed

    private void btnDeleteCoachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCoachActionPerformed
        // TODO add your handling code here:
          int selectedRow = tableCoaches.getSelectedRow();
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a coach to delete!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to delete this coach?", "Confirm Delete", 
            javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE);
            
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tableCoaches.getModel();
        model.removeRow(selectedRow);
        javax.swing.JOptionPane.showMessageDialog(this, "Coach deleted successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_btnDeleteCoachActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCoach1;
    private javax.swing.JButton btnDeleteCoach;
    private javax.swing.JButton btnEditCoach1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tableCoaches;
    // End of variables declaration//GEN-END:variables
}
