/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gymmanagement;

/**
 *
 * @author hp
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel = new javax.swing.JPanel();
        btnManageMembers = new javax.swing.JButton();
        btnSubscriptions = new javax.swing.JButton();
        btnManageCoaches = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebarPanel.setBackground(new java.awt.Color(0, 51, 204));
        sidebarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sidebarPanelMouseEntered(evt);
            }
        });

        btnManageMembers.setBackground(new java.awt.Color(204, 204, 255));
        btnManageMembers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnManageMembers.setForeground(new java.awt.Color(0, 0, 102));
        btnManageMembers.setText("Manage Members");
        btnManageMembers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageMembersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageMembersMouseExited(evt);
            }
        });
        btnManageMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMembersActionPerformed(evt);
            }
        });

        btnSubscriptions.setBackground(new java.awt.Color(204, 204, 255));
        btnSubscriptions.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSubscriptions.setForeground(new java.awt.Color(0, 0, 102));
        btnSubscriptions.setText("Plans");
        btnSubscriptions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubscriptionsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubscriptionsMouseExited(evt);
            }
        });

        btnManageCoaches.setBackground(new java.awt.Color(204, 204, 255));
        btnManageCoaches.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnManageCoaches.setForeground(new java.awt.Color(0, 0, 102));
        btnManageCoaches.setText("Coaches");
        btnManageCoaches.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageCoachesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageCoachesMouseExited(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(204, 204, 255));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 0, 102));
        btnLogout.setText("Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageCoaches, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addComponent(btnManageMembers)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSubscriptions, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnManageMembers)
                .addGap(18, 18, 18)
                .addComponent(btnSubscriptions)
                .addGap(28, 28, 28)
                .addComponent(btnManageCoaches)
                .addGap(27, 27, 27)
                .addComponent(btnLogout)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        getContentPane().add(sidebarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, 350));

        contentPanel.setBackground(new java.awt.Color(204, 204, 255));
        contentPanel.setName("contentPanel"); // NOI18N
        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("شاشة التحكم الرئيسية - الرجاء اختيار قسم من القائمة الجانبية");
        contentPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 6, -1, 36));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\oop project gym\\logo.png")); // NOI18N
        contentPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, 147));

        getContentPane().add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 440, 350));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel1.setText("Welcome to Gym Management Dashboard");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 520, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sidebarPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebarPanelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_sidebarPanelMouseEntered

    private void btnManageMembersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageMembersMouseEntered
     
        // TODO add your handling code here:
        // لمّا الماوس يخش فوق الزر: غير لونه للون مضيء (مثلاً أزرق فاتح أو رمادي فاتح)
        btnManageMembers.setBackground(new java.awt.Color(52, 152, 219)); 
        btnManageMembers.setOpaque(true); // تفعيل اللون عشان يظهر الإضاءة
    }//GEN-LAST:event_btnManageMembersMouseEntered

    private void btnManageMembersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageMembersMouseExited
        // TODO add your handling code here:
        // لمّا الماوس يطلع من الزر: رجعه شفاف أو للونه الأصلي الطافي
        btnManageMembers.setOpaque(false); // لو كنتِ مخلتيه شفاف
        // أو لو تبّي لون محدد طافي: 
        btnManageMembers.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_btnManageMembersMouseExited

    private void btnSubscriptionsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubscriptionsMouseExited
        // TODO add your handling code here:
        // لمّا الماوس يطلع من الزر: رجعه شفاف أو للونه الأصلي الطافي
        btnSubscriptions.setOpaque(false); // لو كنتِ مخلتيه شفاف
        // أو لو تبّي لون محدد طافي: 
        btnSubscriptions.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_btnSubscriptionsMouseExited

    private void btnSubscriptionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubscriptionsMouseEntered
        // TODO add your handling code here:
         // لمّا الماوس يخش فوق الزر: غير لونه للون مضيء (مثلاً أزرق فاتح أو رمادي فاتح)
        btnSubscriptions.setBackground(new java.awt.Color(52, 152, 219)); 
        btnSubscriptions.setOpaque(true); // تفعيل اللون عشان يظهر الإضاءة
    }//GEN-LAST:event_btnSubscriptionsMouseEntered

    private void btnManageCoachesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageCoachesMouseEntered
        // TODO add your handling code here:
        // لمّا الماوس يخش فوق الزر: غير لونه للون مضيء (مثلاً أزرق فاتح أو رمادي فاتح)
        btnManageCoaches.setBackground(new java.awt.Color(52, 152, 219)); 
        btnManageCoaches.setOpaque(true); // تفعيل اللون عشان يظهر الإضاءة
    }//GEN-LAST:event_btnManageCoachesMouseEntered

    private void btnManageCoachesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageCoachesMouseExited
        // TODO add your handling code here:
        // لمّا الماوس يطلع من الزر: رجعه شفاف أو للونه الأصلي الطافي
        btnManageCoaches.setOpaque(false); // لو كنتِ مخلتيه شفاف
        // أو لو تبّي لون محدد طافي: 
        btnManageCoaches.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_btnManageCoachesMouseExited

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        // لمّا الماوس يخش فوق الزر: غير لونه للون مضيء (مثلاً أزرق فاتح أو رمادي فاتح)
        btnLogout.setBackground(new java.awt.Color(52, 152, 219)); 
        btnLogout.setOpaque(true); // تفعيل اللون عشان يظهر الإضاءة
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        // لمّا الماوس يطلع من الزر: رجعه شفاف أو للونه الأصلي الطافي
        btnLogout.setOpaque(false); // لو كنتِ مخلتيه شفاف
        // أو لو تبّي لون محدد طافي: 
        btnLogout.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnManageMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMembersActionPerformed
        // TODO add your handling code here:
         showPanel(new MembersPanel());
    }//GEN-LAST:event_btnManageMembersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageCoaches;
    private javax.swing.JButton btnManageMembers;
    private javax.swing.JButton btnSubscriptions;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel sidebarPanel;
    // End of variables declaration//GEN-END:variables
    
   private void showPanel(javax.swing.JPanel panel) {
    if (contentPanel != null) {
        contentPanel.removeAll();
        
        // 1. تحديد الحجم والتموضع بدقة (يبدأ من النقطة 0,0)
        panel.setBounds(0, 0, contentPanel.getWidth(), contentPanel.getHeight());
        
        // 2. 🌟 التعديل السحري: إخبار الـ AbsoluteLayout بمكان وأبعاد العنصر أثناء الإضافة
        contentPanel.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, contentPanel.getWidth(), contentPanel.getHeight()));
        
        // 3. تحديث الواجهة
        contentPanel.repaint();
        contentPanel.revalidate();
    }
}
    
}
