/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gymmanagement;

/**
 *
 * @author hp
 */
public class MembersPanel extends javax.swing.JPanel {

    /**
     * Creates new form MembersPanel
     */
    public MembersPanel() {
        initComponents();
        // 1. جعل الجدول يوزع المساحة تلقائياً بالتساوي على الأعمدة
        tableMembers.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);

         // 2. إجبار الأعمدة على إعادة حساب أحجامها بالتساوي فوراً
         tableMembers.doLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMembers = new javax.swing.JTable();
        btnAddMember = new javax.swing.JButton();
        btnEditMember = new javax.swing.JButton();
        btnDeleteMember = new javax.swing.JButton();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setText("  Manage Members   ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 47));

        tableMembers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Number Phone", "Subscription"
            }
        ));
        tableMembers.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tableMembers);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 320, 150));

        btnAddMember.setBackground(new java.awt.Color(204, 204, 255));
        btnAddMember.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnAddMember.setText("Add Member");
        btnAddMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMemberActionPerformed(evt);
            }
        });
        add(btnAddMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 110, 30));

        btnEditMember.setBackground(new java.awt.Color(204, 204, 255));
        btnEditMember.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnEditMember.setText("Edit Data");
        btnEditMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditMemberActionPerformed(evt);
            }
        });
        add(btnEditMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        btnDeleteMember.setBackground(new java.awt.Color(204, 204, 255));
        btnDeleteMember.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnDeleteMember.setText("Delete");
        btnDeleteMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMemberActionPerformed(evt);
            }
        });
        add(btnDeleteMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMemberActionPerformed
        // TODO add your handling code here:
         
         
        java.awt.Frame parentFrame = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
        javax.swing.table.DefaultTableModel subModel = gymmanagement.SubscriptionPanel.getSubscriptionTableModel();
    
        AddMemberDialog dialog;
         if (subModel != null) {
        dialog = new AddMemberDialog(parentFrame, true, subModel);
    } else {
            dialog = new AddMemberDialog(parentFrame, true);
        }
    
          // إظهار الشاشة
          dialog.setVisible(true);
    
        // 4. بعد إغلاق الشاشة، نتحققوا لو المستخدم ضغط على Save
        if (dialog.isSucceeded()) {
        // نسحبوا البيانات من الـ Dialog
        String name = dialog.getMemberName();
        String phone = dialog.getMemberPhone();
        String subscription = dialog.getSelectedSubscription();
        
        // نضيفوا الصف الجديد في جدول الأعضاء (تأكدي من اسم الجدول عندك، افترضناه tableMembers)
        javax.swing.table.DefaultTableModel memberModel = (javax.swing.table.DefaultTableModel) tableMembers.getModel();
        memberModel.addRow(new Object[]{name, phone, subscription});
        
        javax.swing.JOptionPane.showMessageDialog(this, "تم إضافة العضو بنجاح!", "نجاح", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_btnAddMemberActionPerformed

    private void btnEditMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditMemberActionPerformed
        // TODO add your handling code here:
        
    // 1. التحقق من أن المستخدم حدد صفاً من الجدول (تأكدي من اسم الجدول tableMembers)
        int selectedRow = tableMembers.getSelectedRow();
        if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "الرجاء تحديد عضو من الجدول لتعديله!", "تنبيه", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
         // 2. سحب البيانات الحالية من الصف المحدد
        String currentName = tableMembers.getValueAt(selectedRow, 0).toString();
        String currentPhone = tableMembers.getValueAt(selectedRow, 1).toString();
        String currentPlan = tableMembers.getValueAt(selectedRow, 2).toString();
    
        // 3. فتح الـ Dialog وتمرير البيانات ليه
        java.awt.Frame parentFrame = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
        javax.swing.table.DefaultTableModel subModel = gymmanagement.SubscriptionPanel.getSubscriptionTableModel();
    
        AddMemberDialog dialog = (subModel != null) ? new AddMemberDialog(parentFrame, true, subModel) : new AddMemberDialog(parentFrame, true);
    
        // تمرير البيانات للشاشة عشان تطلع معبية تلقائياً
        dialog.setMemberData(currentName, currentPhone, currentPlan);
         dialog.setVisible(true);
    
         // 4. بعد إغلاق الشاشة، لو ضغط على الحفظ (Update) نحدثوا الجدول فوراً
        if (dialog.isSucceeded()) {
            tableMembers.setValueAt(dialog.getMemberName(), selectedRow, 0);
            tableMembers.setValueAt(dialog.getMemberPhone(), selectedRow, 1);
            tableMembers.setValueAt(dialog.getSelectedSubscription(), selectedRow, 2);
        
            javax.swing.JOptionPane.showMessageDialog(this, "تم تعديل بيانات العضو بنجاح!", "نجاح", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnEditMemberActionPerformed

    private void btnDeleteMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMemberActionPerformed
        // TODO add your handling code here:
        
    // 1. التحقق من تحديد صف
    int selectedRow = tableMembers.getSelectedRow();
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "الرجاء تحديد عضو من الجدول لحذفه!", "تنبيه", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // 2. رسالة تأكيد الحذف
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "هل أنتِ متأكدة من حذف هذا العضو نهائياً؟", "تأكيد الحذف", 
            javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE);
            
    // 3. لو وافق، نحذفوا الصف من الموديل طول
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tableMembers.getModel();
        model.removeRow(selectedRow);
        javax.swing.JOptionPane.showMessageDialog(this, "تم حذف العضو بنجاح!", "نجاح", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_btnDeleteMemberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMember;
    private javax.swing.JButton btnDeleteMember;
    private javax.swing.JButton btnEditMember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMembers;
    // End of variables declaration//GEN-END:variables
}
