/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gymmanagement;

/**
 *
 * @author hp
 */
public class SubscriptionPanel extends javax.swing.JPanel {
  
    // متغير للتحكم في أسطر وأعمدة الجدول
    private javax.swing.table.DefaultTableModel tableModel;
    /**
     * Creates new form SubscriptionPanel
     */
    public SubscriptionPanel() {
        initComponents();
        // ربط الـ tableModel بالجدول اللي صممتيه
        tableModel = (javax.swing.table.DefaultTableModel) tableSubscriptions.getModel();
        // حفظ الـ Model الخاص بالجدول في المتغير الثابت أول ما تفتح الشاشة
        // (تأكدي من اسم الجدول عندك لو كان tableSubscriptions أو jTable1 وعدليه هنا)
        lastActiveModel = (javax.swing.table.DefaultTableModel) tableSubscriptions.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableSubscriptions = new javax.swing.JTable();
        btnAddSubscription = new javax.swing.JButton();
        btnEditSubscription = new javax.swing.JButton();
        btnDeleteSubscription = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableSubscriptions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subscription Name", "Price", "Duration"
            }
        ));
        jScrollPane1.setViewportView(tableSubscriptions);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 375, 174));

        btnAddSubscription.setBackground(new java.awt.Color(204, 204, 255));
        btnAddSubscription.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnAddSubscription.setText("Add");
        btnAddSubscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSubscriptionActionPerformed(evt);
            }
        });
        add(btnAddSubscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        btnEditSubscription.setBackground(new java.awt.Color(204, 204, 255));
        btnEditSubscription.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnEditSubscription.setText("Edit");
        btnEditSubscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSubscriptionActionPerformed(evt);
            }
        });
        add(btnEditSubscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        btnDeleteSubscription.setBackground(new java.awt.Color(204, 204, 255));
        btnDeleteSubscription.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnDeleteSubscription.setText("Delete");
        btnDeleteSubscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSubscriptionActionPerformed(evt);
            }
        });
        add(btnDeleteSubscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel1.setText("Subscriptions Management");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSubscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSubscriptionActionPerformed
        // TODO add your handling code here:
        // 1. فتح الشاشة المنبثقة في وضع الإضافة
         AddSubscriptionDialog dialog = new AddSubscriptionDialog((java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this), true);
         dialog.setVisible(true);

          // 2. إذا ضغط المستخدم على Save، نسحبوا البيانات ونضيفوها للجدول
        if (dialog.isSaved()) {
            tableModel.addRow(new Object[]{
                dialog.getSubscriptionName(),
                dialog.getPrice() + " LYD", // السعر بالدينار الليبي
                dialog.getDuration()
            });
            javax.swing.JOptionPane.showMessageDialog(this, "Subscription Added Successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
         }
    }//GEN-LAST:event_btnAddSubscriptionActionPerformed

    private void btnEditSubscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSubscriptionActionPerformed
        // TODO add your handling code here:
         // 1. التأكد من أن المستخدم حدد سطر من الجدول لتعديله
        int selectedRow = tableSubscriptions.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a subscription to edit!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. سحب البيانات الحالية من السطر المحدد
         String currentName = tableModel.getValueAt(selectedRow, 0).toString();
         // تحويل السعر من نص إلى رقم (تنظيف الكلمة من " LYD")
         String priceText = tableModel.getValueAt(selectedRow, 1).toString().replace(" LYD", "").trim();
        double currentPrice = Double.parseDouble(priceText);
        String currentDuration = tableModel.getValueAt(selectedRow, 2).toString();

        // 3. فتح الشاشة المنبثقة ويمرر لها البيانات القديمة (الـ Constructor الثاني)
        AddSubscriptionDialog dialog = new AddSubscriptionDialog(
             (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this), 
            true, 
            currentName, 
            currentPrice, 
            currentDuration
         );
        dialog.setVisible(true);

        // 4. إذا ضغط المستخدم حفظ، نحدث البيانات في نفس السطر
        if (dialog.isSaved()) {
            tableModel.setValueAt(dialog.getSubscriptionName(), selectedRow, 0);
            tableModel.setValueAt(dialog.getPrice() + " LYD", selectedRow, 1);
            tableModel.setValueAt(dialog.getDuration(), selectedRow, 2);
            javax.swing.JOptionPane.showMessageDialog(this, "Subscription Updated Successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnEditSubscriptionActionPerformed

    private void btnDeleteSubscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSubscriptionActionPerformed
        // TODO add your handling code here:
         // 1. التأكد من تحديد سطر
        int selectedRow = tableSubscriptions.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a subscription to delete!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

           // 2. تأكيد الحذف من المستخدم
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this subscription?", "Confirm Delete", javax.swing.JOptionPane.YES_NO_OPTION);
    
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            tableModel.removeRow(selectedRow); // حذف السطر من الجدول
            javax.swing.JOptionPane.showMessageDialog(this, "Subscription Deleted Successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
         }
    }//GEN-LAST:event_btnDeleteSubscriptionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSubscription;
    private javax.swing.JButton btnDeleteSubscription;
    private javax.swing.JButton btnEditSubscription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableSubscriptions;
    // End of variables declaration//GEN-END:variables
     // دالة ثابتة تسمح لسحب الـ Model الخاص بجدول الاشتراكات من أي مكان
    private static javax.swing.table.DefaultTableModel lastActiveModel = null;

    public static javax.swing.table.DefaultTableModel getSubscriptionTableModel() {
        return lastActiveModel;
     }

     // حطي السطر هذا داخل الـ Constructor بتاع الـ SubscriptionPanel تحت ()initComponents
    // lastActiveModel = (javax.swing.table.DefaultTableModel) tableSubscriptions.getModel();

}
